2024.08.02: * fixed: **/__init__.sh: wrong parameters line for `tkl_include*` function call * fixed: bash/tacklelib/bash_tacklelib: `tkl_dump_includes_stack` wrong stack order * changed: bash/tacklelib/bash_tacklelib: improvements
2024.07.30:
* new: bash/tacklelib/tools/load_config.sh: `--ignore-unexist` flag to ignore unexisted variables and does not substitute an unexisted variable placeholder with `*:` prefix
* changed: bash/tacklelib/bash_tacklelib: improvements in a path validation
* changed: bash/tacklelib/tools/load_config.sh: improvements
* changed: bash_tests: __init__/__init__.sh, unit/01_bash_tacklelib/02_cast_to_int/test_1.sh: improvements

2024.07.29:
* fixed: bash/tacklelib/bash_tacklelib: execution fixup
* new: bash/tacklelib/testlib.sh: `tkl_test_assert_*_expr` functions to assert all arguments as a command line expression
* changed: bash/tacklelib/testlib.sh: run test case in empty shell environment
* changed: bash/tacklelib/testlib.sh: fall back to lesser variable while detect log output directory: `$TESTS_PROJECT_LOG_ROOT` -> `$PROJECT_LOG_ROOT` -> `$BASH_SOURCE_DIR/.log`
* changed: bash/tacklelib/testlib.sh: improvements

diff --git a/bash/tacklelib/bash_tacklelib b/bash/tacklelib/bash_tacklelib
--- a/bash/tacklelib/bash_tacklelib
+++ b/bash/tacklelib/bash_tacklelib
@@ -428,7 +428,7 @@ function tkl_false()
 #
 function tkl_set_return()
 {
-  tkl_if_int "$1" || return 255
+  tkl_if_int "${1:-0}" || return 255
   return ${1:-0}
 }
 
@@ -549,14 +549,14 @@ function tkl_dump_includes_stack()
 
   echo "  [00] ${BASH_SOURCE_CMD_LINE_ARR[0]}:"
   for (( i=1; i < ${#BASH_SOURCE_CMD_LINE_ARR[@]}; i++ )); do
-    echo "          [${zeros:${#k}-1}$k]=\`${BASH_SOURCE_CMD_LINE_ARR[k]}\`"
+    echo "       [${zeros:${#k}-1}$k]=\`${BASH_SOURCE_CMD_LINE_ARR[k]}\`"
   done
 
-  for (( i=0; i < stack_size; i++ )); do
+  for (( i=stack_size; --i >= 0; )); do
     if (( tkl__vars_stack__global__BASH_SOURCE_CMD_LINE__${i}__defined )); then
       eval tkl_deserialize_array "\${tkl__vars_stack__global__BASH_SOURCE_CMD_LINE__$i}" cmd_line_arr
 
-      (( j = i + 1 ))
+      (( j = stack_size - i ))
       echo "  [${zeros:${#j}-1}$j] ${cmd_line_arr[0]}:"
       for (( j=1; j < ${#cmd_line_arr[@]}; j++ )); do
         (( k = j - 1 ))
@@ -813,7 +813,9 @@ function tkl_make_source_file_components()
   tkl_export BASH_SOURCE_FILE "$RETURN_VALUE"
 
   local bash_source_file_name="${BASH_SOURCE_FILE##*[/]}"
-  [[ -z "$bash_source_file_name" ]] && bash_source_file_name="$BASH_SOURCE_FILE"
+  if [[ -z "$bash_source_file_name" ]]; then
+    bash_source_file_name="$BASH_SOURCE_FILE"
+  fi
 
   tkl_export BASH_SOURCE_FILE_NAME "$bash_source_file_name"
   tkl_export BASH_SOURCE_DIR "${BASH_SOURCE_FILE%[/]*}"
@@ -827,12 +829,14 @@ function tkl_make_source_file_components()
 
 function tkl_declare_source_file_components_from_args()
 {
-  [[ -z "$BASH_SOURCE_NEST_LVL" ]] && tkl_export BASH_SOURCE_NEST_LVL 0
+  [[ -n "$BASH_SOURCE_NEST_LVL" ]] || tkl_export BASH_SOURCE_NEST_LVL 0
 
   tkl_export BASH_SOURCE_FILE "$1"
 
   local bash_source_file_name="${BASH_SOURCE_FILE##*[/]}"
-  [[ -z "$bash_source_file_name" ]] && bash_source_file_name="$BASH_SOURCE_FILE"
+  if [[ -z "$bash_source_file_name" ]]; then
+    bash_source_file_name="$BASH_SOURCE_FILE"
+  fi
 
   tkl_export BASH_SOURCE_FILE_NAME "$bash_source_file_name"
   tkl_export BASH_SOURCE_DIR "${BASH_SOURCE_FILE%[/]*}"
@@ -846,9 +850,7 @@ function tkl_declare_source_file_components_from_args()
 
 function tkl_pushset_source_file_components()
 {
-  if [[ -z "$BASH_SOURCE_NEST_LVL" ]]; then
-    tkl_export BASH_SOURCE_NEST_LVL 0
-  fi
+  [[ -n "$BASH_SOURCE_NEST_LVL" ]] || tkl_export BASH_SOURCE_NEST_LVL 0
 
   (( BASH_SOURCE_NEST_LVL++ ))
 
@@ -861,7 +863,9 @@ function tkl_pushset_source_file_components()
   tkl_pushset_var_to_stack global BASH_SOURCE_FILE "$1"
 
   local bash_source_file_name="${BASH_SOURCE_FILE##*[/]}"
-  [[ -z "$bash_source_file_name" ]] && bash_source_file_name="$BASH_SOURCE_FILE"
+  if [[ -z "$bash_source_file_name" ]]; then
+    bash_source_file_name="$BASH_SOURCE_FILE"
+  fi
 
   tkl_pushset_var_to_stack global BASH_SOURCE_FILE_NAME "$bash_source_file_name"
   tkl_pushset_var_to_stack global BASH_SOURCE_DIR "${BASH_SOURCE_FILE%[/]*}"
@@ -926,6 +930,9 @@ function tkl_include()
       tkl_set_return $_84CB4B34_last_error
       tkl_include_local_impl "$RETURN_VALUE" "${@:2}"
       _84CB4B34_last_error=$?
+    else
+      echo "${FUNCNAME[0]}: error: invalid inclusion path: \`$1\`." >&2
+      tkl_abort "$_84CB4B34_last_error"
     fi
   else
     local _84CB4B34_included=0
@@ -941,14 +948,12 @@ function tkl_include()
         ;;
       esac
       for _84CB4B34_path_prefix in $BASH_SOURCE_PATH; do
-        if tkl_get_abs_path "$_84CB4B34_path_prefix/$1" && tkl_convert_backend_path_to_native "$RETURN_VALUE" -s; then
-          if [[ -f "$RETURN_VALUE" ]]; then
-            _84CB4B34_included=1
-            tkl_set_return $_84CB4B34_last_error
-            tkl_include_local_impl "$RETURN_VALUE" "${@:2}"
-            _84CB4B34_last_error=$?
-            break
-          fi
+        if tkl_get_abs_path "$_84CB4B34_path_prefix/$1" && tkl_convert_backend_path_to_native "$RETURN_VALUE" -s && [[ -f "$RETURN_VALUE" ]]; then
+          _84CB4B34_included=1
+          tkl_set_return $_84CB4B34_last_error
+          tkl_include_local_impl "$RETURN_VALUE" "${@:2}"
+          _84CB4B34_last_error=$?
+          break
         fi
       done
     fi
@@ -959,6 +964,9 @@ function tkl_include()
         tkl_set_return $_84CB4B34_last_error
         tkl_include_local_impl "$RETURN_VALUE" "${@:2}"
         _84CB4B34_last_error=$?
+      else
+        echo "${FUNCNAME[0]}: error: invalid inclusion path: \`$1\`." >&2
+        tkl_abort "$_84CB4B34_last_error"
       fi
     fi
   fi
@@ -1103,6 +1111,11 @@ function tkl_get_abs_path()
 
   local BasePath="$1"
   local RelativePath="$2"
+
+  # check on globbing characters
+  if [[ "${BasePath//\*/}" != "$BasePath" || "${BasePath//\?/}" != "$BasePath" ]]; then
+    return 1
+  fi
 
   # drop line returns
   BasePath="${BasePath//[$'\r\n']}"
@@ -1458,7 +1471,12 @@ function tkl_normalize_path()
   # set return value to input value
   RETURN_VALUE="$path_to_normalize"
 
-  [[ -z "$path_to_normalize" ]] && return 1
+  # with check on globbing characters
+  if [[ -z "$path_to_normalize" ]]; then
+    return 1
+  elif [[ "${BasePath//\*/}" != "$BasePath" || "${BasePath//\?/}" != "$BasePath" ]]; then
+    return 2
+  fi
 
   local num_reductions
   local path_prefix
